name: dev server workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{secrets.VERCEL_APP_ORG_ID}}
      VERCEL_PROJECT_ID: ${{secrets.VERCEL_APP_PROJECT_ID}}
      VERCEL_TOKEN: ${{secrets.VERCEL_APP_TOKEN}}
    steps:
      - name: checks out repository
        uses: actions/checkout@v2
      - name: Install node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.13.1"
      - name: Install project dependencies
        run: npm install
      - name: Build the project
        run: npm run build
      - name: Deploy to vercel
        run: npm run build-vercel
  test-app:
    run: echo "Hello World"
